version: "2"
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PYTHON_ENV='production'
      - NODE_ENV='production'
    command: bash /code/start-docker.sh
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
